require("plugins.lsp")
require("plugins.cmp")
require("plugins.gitsigns")
require("plugins.luasnip")
require("plugins.whichkey")
require("plugins.formatter")
-- require("plugins.none-ls")
-- require("plugins.nvim-tree")
-- require("plugins.indent")
-- require("plugins.qmk-formatter")
require("plugins.tree-sitter")
