require("plugins.gitsigns")
require("plugins.luasnip")
require("plugins.whichkey")
require("plugins.lsp")
-- require("plugins.formatter")
require("plugins.none-ls")
require("plugins.nvim-tree")
require("plugins.indent")
require("qmk-formatter")
